# This is an example docker compose file
# Please update this file to match your setup
services:
  chiron-relay:
    build: .
    env_file:
      - .env # Replace this with the path to your env file
    ports:
      - "8080:8080" # Host Port:Container Port
    volumes:
      # 1. Create a folder name "secrets" in the root of this project
      # 2. Place your account.json in the "secrets" folder
      # 3. The account.json will be mounted as a read only file in the container's secrets folder
      - ./secrets/account.json:/run/secrets/account.json:ro